cors.allowed-origins=http://localhost:3000

newschart.nyt.enabled=false
newschart.gemini.enabled=false
newschart.openrouter-configs[0].source=PERPLEXITY
newschart.openrouter-configs[0].model=perplexity/sonar-pro-search
newschart.openrouter-configs[0].enabled=false
newschart.openrouter-configs[0].fetch-delay-seconds=15

newschart.openrouter-configs[1].source=OPENAI
newschart.openrouter-configs[1].model=~openai/gpt-mini-latest:online
newschart.openrouter-configs[1].enabled=false
newschart.openrouter-configs[1].fetch-delay-seconds=20

newschart.openrouter-configs[2].source=ANTHROPIC
newschart.openrouter-configs[2].model=~anthropic/claude-haiku-latest:online
newschart.openrouter-configs[2].enabled=false
newschart.openrouter-configs[2].fetch-delay-seconds=25

newschart.openrouter-configs[3].source=XAI
newschart.openrouter-configs[3].model=x-ai/grok-4.3:online
newschart.openrouter-configs[3].enabled=false
newschart.openrouter-configs[3].fetch-delay-seconds=30
