spring.application.name=newschart

cors.allowed-origins=https://newschart.rossarnold.uk

spring.ai.google.genai.api-key=${GOOGLE_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash-lite

management.endpoints.web.exposure.include=prometheus,health
management.metrics.tags.application=${spring.application.name}

spring.ai.openai.api-key=${OPENROUTER_API_KEY}
spring.ai.openai.base-url=https://openrouter.ai/api/v1
spring.ai.openai.embedding.enabled=false

newschart.openrouter-configs[0].source=PERPLEXITY
newschart.openrouter-configs[0].model=perplexity/sonar-pro-search
newschart.openrouter-configs[0].enabled=true
newschart.openrouter-configs[0].fetch-delay-seconds=15

newschart.openrouter-configs[1].source=OPENAI
newschart.openrouter-configs[1].model=openai/gpt-4o-search-preview
newschart.openrouter-configs[1].enabled=true
newschart.openrouter-configs[1].fetch-delay-seconds=20

newschart.openrouter-configs[2].source=ANTHROPIC
newschart.openrouter-configs[2].model=~anthropic/claude-haiku-latest:online
newschart.openrouter-configs[2].enabled=true
newschart.openrouter-configs[2].fetch-delay-seconds=25

newschart.openrouter-configs[3].source=XAI
newschart.openrouter-configs[3].model=x-ai/grok-4.3:online
newschart.openrouter-configs[3].enabled=true
newschart.openrouter-configs[3].fetch-delay-seconds=30