spring.application.name=newschart

spring.ai.google.genai.api-key=${GOOGLE_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash-lite

management.endpoints.web.exposure.include=prometheus,health
management.metrics.tags.application=${spring.application.name}